services:
  back:
    build: ./back
    ports:
      - "8080:8080"
    env_file:
      - ./back/.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  front:
    build:
      context: ./front
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - back
