services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  back:
    build: ./back
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=mongodb://mongo:27017/apitodo
      - JWT_SECRET=dGhpcy1pcy1hLWRldi1zZWNyZXQta2V5LWZvci1qd3QtYXBpLXRvZG8tMjAyNi1tYXJjb3MtdmVyeS1zZWN1cmU=
    depends_on:
      - mongo

  front:
    build:
      context: ./front
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - back

volumes:
  mongo_data:
